sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=config-centos-6
  - INSTANCE=config-centos-7
  - INSTANCE=config-fedora-latest
  - INSTANCE=config-debian-7
  - INSTANCE=config-debian-8
  - INSTANCE=config-ubuntu-1404
  - INSTANCE=config-ubuntu-1604
  - INSTANCE=module22-centos-6
  - INSTANCE=module22-debian-7
  - INSTANCE=module24-centos-7
  - INSTANCE=module24-fedora-latest
  - INSTANCE=module24-debian-8
  - INSTANCE=module24-ubuntu-1404
  - INSTANCE=module24-ubuntu-1604
  - INSTANCE=module24-opensuse-leap
  - INSTANCE=service22-single-centos-6
  - INSTANCE=service22-single-debian-7
  - INSTANCE=service22-multi-centos-6
  - INSTANCE=service22-multi-debian-7
  - INSTANCE=service24-single-centos-7
  - INSTANCE=service24-single-fedora-latest
  - INSTANCE=service24-single-ubuntu-1404
  - INSTANCE=service24-single-ubuntu-1604
  - INSTANCE=service24-single-debian-8
  - INSTANCE=service24-single-opensuse-leap
  - INSTANCE=service24-multi-centos-7
  - INSTANCE=service24-multi-fedora-latest
  - INSTANCE=service24-multi-debian-8
  - INSTANCE=service24-multi-ubuntu-1404
  - INSTANCE=service24-multi-ubuntu-1604
  - INSTANCE=service24-multi-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
